### ISSUE TITLE
Double Necklace Equips

### ISSUE THREAD

**Issue by MishraAnkh** [genfanad/genfanad-public-bugtracker#127]
![image](https://user-images.githubusercontent.com/10050704/221085505-3005a281-5af9-4d5a-b272-687dcc40f6d7.png)
![image](https://user-images.githubusercontent.com/10050704/221085517-3dd639dd-31d7-427e-9c50-2daf7104e6ef.png)

**Comment by Retoxified** [comment]
Fixed in last update
