### ISSUE TITLE
Monster aggression leashes are capable of griefing others.

### ISSUE THREAD

**Issue by APB-Reloaded** [genfanad/genfanad-public-bugtracker#29]
I wouldn't think this is intended, so allow me to explain by laying out a scenario or two:

Some skillers are minding their own business at some iron rocks. Someone else comes along, maybe to also mine those rocks, but brings an aggressive monster with them.

Walking out of a monster's leash range causes said monster's aggro to snap to one of the skillers, starting a combat phase they were likely not equipped for.
-----------------------------------------------------------------------------------------------------------------------------
This can also cause threat to snap towards players whos' combat levels exceed the monster's by at least 8 levels.  If someone is AFK'ing melee combat with a group of monsters, any that are not engaged in combat can snap their aggro towards ANY nearby player regardless of level.

This, in my opinion, can become a critical issue if the game's population rises by a substantial amount.

**Comment by 1abell** [comment]
quit ruining the game

**Comment by Heleor** [comment]
This should be fixed now.
