### ISSUE TITLE
Smithed item disappearing

### ISSUE THREAD

**Issue by RawlinStone** [genfanad/genfanad-public-bugtracker#32]
When trying to smith the cracked sword +1, 3 swords disappeared (2 said I made it successfully, 1 was broken).

So 2 of them glitched out. It gave me back the scrap metal each time.

**Comment by rossmas** [comment]
Use the NPC by the anvil instead - no failure. I agree it seems to be a bug though.

**Comment by eviltwigster** [comment]
Similar issue with the early game armour - shield, body and legs all eaten up by apparent successful +1, relogged after first one, tried dropping and farming fresh scrap metal, still no good.

**Comment by Satharis** [comment]
Duplicate of https://github.com/genfanad/genfanad-public-bugtracker/issues/13
