### ISSUE TITLE
Scroll to zoom not working

### ISSUE THREAD

**Issue by SupahSoftware** [genfanad/genfanad-public-bugtracker#33]
I am running the game on Windows via Chrome.

Apparently scroll to zoom is a feature, but it is not working for me

> Finally, you can zoom in and out using the mouse wheel-- has that not been working with you? If not, that might be a bug. You can report it here: https://github.com/genfanad/genfanad-public-bugtracker/issues

**Comment by Satharis** [comment]
The scrolling is actually not a feature of the game it's something chrome does so you'd have to look into that as to why it isn't working for you.
