### ISSUE TITLE
undefined bank slot

### ISSUE THREAD

**Issue by winglift** [genfanad/genfanad-public-bugtracker#36]
After the latest 14/10/2022 big patch, I've noticed this bank slot is unable withdraw or clear. Examining this item 'undefined'

![image](https://user-images.githubusercontent.com/115888462/195995650-5bac1356-db4d-4178-823a-c025be77e3e7.png)

**Comment by Satharis** [comment]
@winglift Are you still having this issue even after ctrl+f5 refreshing the client?

**Comment by winglift** [comment]
Hi Satharis

Yes I've tried refreshing Cache several times before.

**Comment by Heleor** [comment]
Please file a ticket with your account id. Undefined items are items that have been deleted, and we have to clean them out manually!
