### ISSUE TITLE
Items Disappearing

### ISSUE THREAD

**Issue by Gallus-RSPS** [genfanad/genfanad-public-bugtracker#4]
While butchering chickens, it says in the chat bot that I successfully butcher it, yet the entire item disappears.

**Comment by rstan122** [comment]
When butchering a chicken, a success can also result in feathers, which would just go to the existing stack.  If your inventory is full and you have a butchering success for 2 or more chickens, you will fill your inventory, the excess seems to be lost and the butchering process will stop, even if other carcasses are in queue.
