### ISSUE TITLE
Player/NPC drop shadows render on top of terrain when character is hidden behind it.

### ISSUE THREAD

**Issue by SnowyToo** [genfanad/genfanad-public-bugtracker#41]
See attached image.
This happens even when the character is inside a building, the walls/roof of which would normally hide the drop shadow.
![image](https://user-images.githubusercontent.com/34379309/196284480-91707416-2bd8-43f1-a9b3-08aea5dc3a79.png)

**Comment by Satharis** [comment]
Known bug/engine limitation at the moment.
