### ISSUE TITLE
L.Q.  Beef and Potato Sprite/Png

### ISSUE THREAD

**Issue by Frigidfrost** [genfanad/genfanad-public-bugtracker#56]
The L.Q. /H.Q Beef and Potato (or other high quantity items with quality versions) don't visibly show the L.Q/H.Q. arrow in the UI.
<img width="145" alt="L Q  Potato and Beef" src="https://user-images.githubusercontent.com/116538271/197449884-05be47fc-8cc6-4cc5-818b-e8ae55fe30ec.PNG">

**Comment by Frigidfrost** [comment]
Arrows should be moved to a visible location - like the bottom right instead of under the numbers.

**Comment by Heleor** [comment]
This should now be fixed.
