### ISSUE TITLE
Weapon Stats observations - Suggestion

### ISSUE THREAD

**Issue by MishraAnkh** [genfanad/genfanad-public-bugtracker#71]
Submitted on Behalf of Baldrat:
There appears to be a mistake with the weapon stats on the steel mace. The item in question is specifically the HQ version as I do not hold other qualities.
The current stats are 7Aim/18Power when they should be 7Aim/20Power. I came to this conclusion by comparing it to previous weapon tiers such as Iron and cross examining it with the stats of longswords. There is no mistake with the aim stat so I will not cover it.
Firstly ill compare the stats of HQ iron longsword and HQ steel longsword. HQ Iron longsword stats 7Aim/8Power. HQ steel longsword 8Aim/16 power = 100% increase to power.
Now compare HQ iron mace to HQ steel mace. HQ iron mace 6Aim/10Power. Steel mace 7Aim/18Power = 80% increase to power.
The mace felt like an upgrade in the iron tier but the loss of 20% power inside the steel weapons tier makes this weapon not worth using currently over others which all received 100% power increases from the iron tier.
Thank you for reading as this could be a mistake with other weapons and tiers.

**Comment by Heleor** [comment]
All weapon stats will be rebalanced in the next update.
